#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
# config/routes.yaml
user_registration:
    path: /register
    controller: App\Controller\SecurityController::register


